group: deprecated-2017Q4
lang: ruby
rvm:
- 2.3.6
bundler_args: "--system"
env:
  global:
  - GH_REF: github.com/McGill-ECSE429-Fall2018/Tutorial-Lecture-Notes 
branches:
  only:
  - master
script:
- "./convert.sh"
- "./deploy.sh"
